### ISSUE TITLE
dagmenu fail while looping maya menus

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/mgear_core#41]
I get this error if the dag menu is active while loading mGear. This stops mgear menu to be populated correctly
```
# Error: TypeError: file C:\datawork\mgear_dev\mgear_dist\release\scripts\mgear\core\dagmenu.py line 560: argument of type 'function' is not iterable #
```

After little research found that some of the menu items are functions or partial functions. Maybe is related to my configuration or some plugin I have intalled
```
<type 'functools.partial'>
<type 'function'>
<type 'instancemethod'>
buildObjectMenuItemsNow "MainPane|viewPanes|modelPanel2|modelPanel2|modelPanel2|modelPanel2ObjectPop"
buildObjectMenuItemsNow "MainPane|viewPanes|modelPanel1|modelPanel1|modelPanel1|modelPanel1ObjectPop"
buildObjectMenuItemsNow "MainPane|viewPanes|modelPanel4|modelPanel4|modelPanel4|modelPanel4ObjectPop"
```

snippet for checking the menu items
```
import maya.cmds as cmds

for maya_menu in cmds.lsUI(menus=True):

        # We now get the menu's post command which is a command used for
        # dag menu
        menu_cmd = cmds.menu(maya_menu, query=True, postMenuCommand=True) or []
        try:
            if "buildObjectMenuItemsNow" in menu_cmd:
                print menu_cmd
        except TypeError:
            print type(menu_cmd)
            # print dir(menu_cmd)
```

I will add a try and except block to avoid this.
@jdrese  please check this. Maybe there is a better solution :)

**Comment by jdrese** [comment]
Hello @miquelcampos 

This is quite strange. I am not getting this issue on netiher my 2018 and 2019 builds.
I think I understand what is going on... 

When I am querying all menu commands to get the one that is called when using the right mouse button (which is a MEL function called **buildObjectMenuItemsNow**). I am filtering if there 
is already an override made by mGear dag menu or not.  Now, I only check if the command was a partial one by doing **if state and type(menu_cmd) != partial**

My guess is that you have something else installed inside Maya that overrides as well one of its default command calls with a Python function...

Now rather than checking if the command is NOT partial on the menu override,  in the last push I just did I removed your try and except and check if the command is actually a unicode Maya one.

Can you please let me know if this works on your side?

Cheers

**Comment by miquelcampos** [comment]
Hello @jdrese 

Yep! that is working well and much more clean! thanks! :D
